pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/devkelzs/aws-devops-pipeline.git'
            }
        }

        stage('Run Ansible Playbook from Local Jenkins') {
            steps {
                sh '''
                    echo "Running Ansible playbook from local WSL machine..."
                    cd aws-devops-pipeline-project1/ansible
                    ansible-playbook -i inventory.ini playbook.yml
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed. Check SSH, inventory, or playbook.'
        }
    }
}

}
