pipeline {
    agent any
    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/devkelzs/aws-devops-pipeline.git', branch: 'main'

            }
        }

        stage('Deploy to Web Server') {
            steps {
                sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook.yml'
            }
        }
    }
}
