pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub') 
        DOCKERHUB_USER = "kellynkwain"
        FRONTEND_IMAGE = "${DOCKERHUB_USER}/kellynkwain-ecommerce-frontend"
        BACKEND_IMAGE = "${DOCKERHUB_USER}/kellynkwain-ecommerce-backend"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/devkelzs/aws-devops-pipeline.git'
            }
        }

        stage('Frontend Lint') {
            steps {
                dir('app/frontend') {
                    sh '''
                    npm install
                    npx eslint . --ignore-path .eslintignore
                    '''
                }
            }
        }

        stage('Backend Lint') {
            steps {
                dir('app/backend') {
                    sh '''
                    npm install
                    npx eslint . --ignore-path .eslintignore
                    '''
                }
            }
        }

        stage('Backend Test') {
            steps {
                dir('app/backend') {
                    sh '''
                    npm install
                    npm test
                    '''
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('app/frontend') {
                    sh 'docker build -t $FRONTEND_IMAGE .'
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('app/backend') {
                    sh 'docker build -t $BACKEND_IMAGE .'
                }
            }
        }

        stage('Push Images to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $FRONTEND_IMAGE
                    docker push $BACKEND_IMAGE
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD pipeline succeeded! Code is clean, tested, and deployed."
        }
        failure {
            echo "❌ CI/CD pipeline failed. Check stage logs for more info."
        }
    }
}
